openapi: 3.0.3
info:
  title: API de Reservas Hoteleras
  version: 1.0.0
  description: API para gestionar reservas en hoteles con operaciones CRUD y filtros.

servers:
  - url: http://localhost:3000

paths:
  /api/reservas:
    get:
      summary: Obtener todas las reservas o filtrarlas por query
      parameters:
        - in: query
          name: hotel
          schema:
            type: string
        - in: query
          name: fecha_inicio
          schema:
            type: string
            format: date
        - in:
