components:
  schemas:
    Reserva:
      type: object
      properties:
        id:
          type: integer
          example: 1
        hotel:
          type: string
          example: Hotel No estoy
        tipo_habitacion:
          type: string
          example: doble
        num_huespedes:
          type: integer
          example: 2
        fecha:
          type: string
          format: date
          example: 2023-05-15
        fecha_fin:                 
          type: string
          format: date
          example: 2023-05-20
        estado:
          type: string
          example: confirmada